### PR TITLE
deploy manifest-5.3 to mirrors as well

### PR DESCRIPTION
**Pull request by hishamhm**
Hi @leafo, bringing this to your attention so you can update the mirroring job.

As far as I understand having this up and running should fix https://github.com/luarocks/luarocks/issues/726

Thank you!

### CODE REVIEW

**Comment by italomaia** [comment]
Is there something holding this PR from being merged? It seems quite important to seat around for two months.

**Comment by hishamhm** [comment]
@italomaia I deployed the update myself (fingers crossed!)

The issue seems fixed to me, please confirm!

**Comment by leafo** [comment]
Sorry for missing this, thanks for deploying it

**Comment by italomaia** [comment]
It is. Thanks, guys!

**Pull request merged**
